"""Avatar parameter names VRCFaceTracking drives, and a clash check for our own OSC names.

Generated from VRCFaceTracking (main, v6) with vrcft-module/tests/ParamNames: every
parameter in UnifiedTracking.AllParameters (v1 legacy, v2, eye, head, native).

VRCFaceTracking drives an avatar parameter whose address equals one of these names or
ends with "/<name>" (so "PBG/SmileSad" is driven by VRCFT's "SmileSad"), and for binary
parameters also bools named "<name><number>" and "<name>Negative". Merged parameters and
direct-OSC class outputs must not match any of them, so they can never disturb normal
face tracking.
"""

VRCFT_PARAMETERS = frozenset((
    "BrowDownLeft", "BrowDownLeftNegative", "BrowDownRight", "BrowDownRightNegative", "BrowInnerUpLeft",
    "BrowInnerUpLeftNegative", "BrowInnerUpRight", "BrowInnerUpRightNegative", "BrowOuterUpLeft",
    "BrowOuterUpLeftNegative", "BrowOuterUpRight", "BrowOuterUpRightNegative", "BrowsDown",
    "BrowsDownNegative", "BrowsInnerUp", "BrowsInnerUpNegative", "BrowsOuterUp", "BrowsOuterUpNegative",
    "CheekPuffLeft", "CheekPuffLeftNegative", "CheekPuffRight", "CheekPuffRightNegative", "CheekSquintLeft",
    "CheekSquintLeftNegative", "CheekSquintRight", "CheekSquintRightNegative", "CheekSuck",
    "CheekSuckNegative", "CheeksSquint", "CheeksSquintNegative", "CombinedEyeLid",
    "CombinedEyeLidExpandedNegative", "CombinedEyeLidExpandedSqueezeNegative", "CombinedEyeLidNegative",
    "ExpressionTrackingActive", "EyeLidExpanded", "EyeLidExpandedSqueeze", "EyeSquintLeft",
    "EyeSquintLeftNegative", "EyeSquintRight", "EyeSquintRightNegative", "EyeTrackingActive", "EyeWiden",
    "EyeWidenNegative", "EyesDilation", "EyesDilationNegative", "EyesPupilDiameter",
    "EyesPupilDiameterNegative", "EyesSqueeze", "EyesSqueezeNegative", "EyesSqueezeToggle", "EyesSquint",
    "EyesSquintNegative", "EyesWidenToggle", "EyesX", "EyesXNegative", "EyesY", "EyesYNegative", "JawForward",
    "JawForwardNegative", "JawLeft", "JawLeftNegative", "JawOpen", "JawOpenApe", "JawOpenApeNegative",
    "JawOpenForward", "JawOpenForwardNegative", "JawOpenNegative", "JawOpenOverlay", "JawOpenOverlayNegative",
    "JawOpenPuff", "JawOpenPuffLeft", "JawOpenPuffLeftNegative", "JawOpenPuffNegative", "JawOpenPuffRight",
    "JawOpenPuffRightNegative", "JawOpenSuck", "JawOpenSuckNegative", "JawRight", "JawRightNegative", "JawX",
    "JawXNegative", "LeftEyeLid", "LeftEyeLidExpanded", "LeftEyeLidExpandedNegative",
    "LeftEyeLidExpandedSqueeze", "LeftEyeLidExpandedSqueezeNegative", "LeftEyeLidNegative", "LeftEyeSqueeze",
    "LeftEyeSqueezeNegative", "LeftEyeSqueezeToggle", "LeftEyeWiden", "LeftEyeWidenNegative",
    "LeftEyeWidenToggle", "LeftEyeX", "LeftEyeXNegative", "LeftEyeY", "LeftEyeYNegative", "LipTrackingActive",
    "Max", "MaxNegative", "MouthApeShape", "MouthApeShapeNegative", "MouthDimple", "MouthDimpleLeft",
    "MouthDimpleLeftNegative", "MouthDimpleNegative", "MouthDimpleRight", "MouthDimpleRightNegative",
    "MouthLower", "MouthLowerDownApe", "MouthLowerDownApeNegative", "MouthLowerDownInside",
    "MouthLowerDownInsideNegative", "MouthLowerDownLeft", "MouthLowerDownLeftApe",
    "MouthLowerDownLeftApeNegative", "MouthLowerDownLeftLowerInside", "MouthLowerDownLeftLowerInsideNegative",
    "MouthLowerDownLeftNegative", "MouthLowerDownLeftOverlay", "MouthLowerDownLeftOverlayNegative",
    "MouthLowerDownLeftPout", "MouthLowerDownLeftPoutNegative", "MouthLowerDownLeftPuffLeft",
    "MouthLowerDownLeftPuffLeftNegative", "MouthLowerDownLeftSuck", "MouthLowerDownLeftSuckNegative",
    "MouthLowerDownLowerInside", "MouthLowerDownLowerInsideNegative", "MouthLowerDownOverlay",
    "MouthLowerDownOverlayNegative", "MouthLowerDownPout", "MouthLowerDownPoutNegative", "MouthLowerDownPuff",
    "MouthLowerDownPuffLeft", "MouthLowerDownPuffLeftNegative", "MouthLowerDownPuffNegative",
    "MouthLowerDownPuffRight", "MouthLowerDownPuffRightNegative", "MouthLowerDownRight",
    "MouthLowerDownRightApe", "MouthLowerDownRightApeNegative", "MouthLowerDownRightLowerInside",
    "MouthLowerDownRightLowerInsideNegative", "MouthLowerDownRightNegative", "MouthLowerDownRightOverlay",
    "MouthLowerDownRightOverlayNegative", "MouthLowerDownRightPout", "MouthLowerDownRightPoutNegative",
    "MouthLowerDownRightPuffRight", "MouthLowerDownRightPuffRightNegative", "MouthLowerDownRightSuck",
    "MouthLowerDownRightSuckNegative", "MouthLowerDownSuck", "MouthLowerDownSuckNegative", "MouthLowerInside",
    "MouthLowerInsideNegative", "MouthLowerInsideOverturn", "MouthLowerInsideOverturnNegative",
    "MouthLowerLeft", "MouthLowerLeftNegative", "MouthLowerNegative", "MouthLowerOverlay",
    "MouthLowerOverlayNegative", "MouthLowerOverturn", "MouthLowerOverturnNegative", "MouthLowerRight",
    "MouthLowerRightNegative", "MouthPout", "MouthPoutNegative", "MouthPress", "MouthPressLeft",
    "MouthPressLeftNegative", "MouthPressNegative", "MouthPressRight", "MouthPressRightNegative",
    "MouthRaiserLower", "MouthRaiserLowerNegative", "MouthRaiserUpper", "MouthRaiserUpperNegative",
    "MouthSadLeft", "MouthSadLeftNegative", "MouthSadRight", "MouthSadRightNegative", "MouthSmileLeft",
    "MouthSmileLeftNegative", "MouthSmileRight", "MouthSmileRightNegative", "MouthStretch",
    "MouthStretchLeft", "MouthStretchLeftNegative", "MouthStretchNegative", "MouthStretchRight",
    "MouthStretchRightNegative", "MouthTightener", "MouthTightenerLeft", "MouthTightenerLeftNegative",
    "MouthTightenerNegative", "MouthTightenerRight", "MouthTightenerRightNegative", "MouthUpper",
    "MouthUpperInside", "MouthUpperInsideNegative", "MouthUpperInsideOverturn",
    "MouthUpperInsideOverturnNegative", "MouthUpperLeft", "MouthUpperLeftNegative", "MouthUpperNegative",
    "MouthUpperOverturn", "MouthUpperOverturnNegative", "MouthUpperRight", "MouthUpperRightNegative",
    "MouthUpperUpApe", "MouthUpperUpApeNegative", "MouthUpperUpInside", "MouthUpperUpInsideNegative",
    "MouthUpperUpLeft", "MouthUpperUpLeftApe", "MouthUpperUpLeftApeNegative", "MouthUpperUpLeftNegative",
    "MouthUpperUpLeftOverlay", "MouthUpperUpLeftOverlayNegative", "MouthUpperUpLeftPout",
    "MouthUpperUpLeftPoutNegative", "MouthUpperUpLeftPuffLeft", "MouthUpperUpLeftPuffLeftNegative",
    "MouthUpperUpLeftSuck", "MouthUpperUpLeftSuckNegative", "MouthUpperUpLeftUpperInside",
    "MouthUpperUpLeftUpperInsideNegative", "MouthUpperUpOverlay", "MouthUpperUpOverlayNegative",
    "MouthUpperUpPout", "MouthUpperUpPoutNegative", "MouthUpperUpPuff", "MouthUpperUpPuffLeft",
    "MouthUpperUpPuffLeftNegative", "MouthUpperUpPuffNegative", "MouthUpperUpPuffRight",
    "MouthUpperUpPuffRightNegative", "MouthUpperUpRight", "MouthUpperUpRightApe",
    "MouthUpperUpRightApeNegative", "MouthUpperUpRightNegative", "MouthUpperUpRightOverlay",
    "MouthUpperUpRightOverlayNegative", "MouthUpperUpRightPout", "MouthUpperUpRightPoutNegative",
    "MouthUpperUpRightPuffRight", "MouthUpperUpRightPuffRightNegative", "MouthUpperUpRightSuck",
    "MouthUpperUpRightSuckNegative", "MouthUpperUpRightUpperInside", "MouthUpperUpRightUpperInsideNegative",
    "MouthUpperUpSuck", "MouthUpperUpSuckNegative", "MouthUpperUpUpperInside",
    "MouthUpperUpUpperInsideNegative", "MouthX", "MouthXNegative", "NoseSneer", "NoseSneerLeft",
    "NoseSneerLeftNegative", "NoseSneerNegative", "NoseSneerRight", "NoseSneerRightNegative",
    "PuffLeftLowerOverturn", "PuffLeftLowerOverturnNegative", "PuffLeftOverturn", "PuffLeftOverturnNegative",
    "PuffLeftUpperOverturn", "PuffLeftUpperOverturnNegative", "PuffLowerOverturn",
    "PuffLowerOverturnNegative", "PuffOverturn", "PuffOverturnNegative", "PuffRightLowerOverturn",
    "PuffRightLowerOverturnNegative", "PuffRightOverturn", "PuffRightOverturnNegative",
    "PuffRightUpperOverturn", "PuffRightUpperOverturnNegative", "PuffSuck", "PuffSuckLeft",
    "PuffSuckLeftNegative", "PuffSuckNegative", "PuffSuckRight", "PuffSuckRightNegative", "PuffUpperOverturn",
    "PuffUpperOverturnNegative", "RightEyeLid", "RightEyeLidExpanded", "RightEyeLidExpandedNegative",
    "RightEyeLidExpandedSqueeze", "RightEyeLidExpandedSqueezeNegative", "RightEyeLidNegative",
    "RightEyeSqueeze", "RightEyeSqueezeNegative", "RightEyeSqueezeToggle", "RightEyeWiden",
    "RightEyeWidenNegative", "RightEyeWidenToggle", "RightEyeX", "RightEyeXNegative", "RightEyeY",
    "RightEyeYNegative", "SmileApe", "SmileApeNegative", "SmileLeftApe", "SmileLeftApeNegative",
    "SmileLeftLowerOverturn", "SmileLeftLowerOverturnNegative", "SmileLeftOverlay",
    "SmileLeftOverlayNegative", "SmileLeftOverturn", "SmileLeftOverturnNegative", "SmileLeftPout",
    "SmileLeftPoutNegative", "SmileLeftUpperOverturn", "SmileLeftUpperOverturnNegative", "SmileLowerOverturn",
    "SmileLowerOverturnNegative", "SmileOverlay", "SmileOverlayNegative", "SmileOverturn",
    "SmileOverturnNegative", "SmilePout", "SmilePoutNegative", "SmileRightApe", "SmileRightApeNegative",
    "SmileRightLowerOverturn", "SmileRightLowerOverturnNegative", "SmileRightOverlay",
    "SmileRightOverlayNegative", "SmileRightOverturn", "SmileRightOverturnNegative", "SmileRightPout",
    "SmileRightPoutNegative", "SmileRightUpperOverturn", "SmileRightUpperOverturnNegative", "SmileSad",
    "SmileSadLeft", "SmileSadLeftNegative", "SmileSadNegative", "SmileSadRight", "SmileSadRightNegative",
    "SmileUpperOverturn", "SmileUpperOverturnNegative", "TongueDown", "TongueDownLeftMorph",
    "TongueDownLeftMorphNegative", "TongueDownNegative", "TongueDownRightMorph",
    "TongueDownRightMorphNegative", "TongueLeft", "TongueLeftNegative", "TongueLongStep1",
    "TongueLongStep1Negative", "TongueLongStep2", "TongueLongStep2Negative", "TongueRight",
    "TongueRightNegative", "TongueRoll", "TongueRollNegative", "TongueSteps", "TongueStepsNegative",
    "TongueUp", "TongueUpLeftMorph", "TongueUpLeftMorphNegative", "TongueUpNegative", "TongueUpRightMorph",
    "TongueUpRightMorphNegative", "TongueX", "TongueXNegative", "TongueY", "TongueYNegative", "v2/",
    "v2/BrowDown", "v2/BrowDownLeft", "v2/BrowDownLeftNegative", "v2/BrowDownNegative", "v2/BrowDownRight",
    "v2/BrowDownRightNegative", "v2/BrowExpression", "v2/BrowExpressionLeft", "v2/BrowExpressionLeftNegative",
    "v2/BrowExpressionNegative", "v2/BrowExpressionRight", "v2/BrowExpressionRightNegative", "v2/BrowInnerUp",
    "v2/BrowInnerUpLeft", "v2/BrowInnerUpLeftNegative", "v2/BrowInnerUpNegative", "v2/BrowInnerUpRight",
    "v2/BrowInnerUpRightNegative", "v2/BrowLowererLeft", "v2/BrowLowererLeftNegative", "v2/BrowLowererRight",
    "v2/BrowLowererRightNegative", "v2/BrowOuterUp", "v2/BrowOuterUpLeft", "v2/BrowOuterUpLeftNegative",
    "v2/BrowOuterUpNegative", "v2/BrowOuterUpRight", "v2/BrowOuterUpRightNegative", "v2/BrowPinchLeft",
    "v2/BrowPinchLeftNegative", "v2/BrowPinchRight", "v2/BrowPinchRightNegative", "v2/BrowUp",
    "v2/BrowUpLeft", "v2/BrowUpLeftNegative", "v2/BrowUpNegative", "v2/BrowUpRight", "v2/BrowUpRightNegative",
    "v2/CheekPuffLeft", "v2/CheekPuffLeftNegative", "v2/CheekPuffRight", "v2/CheekPuffRightNegative",
    "v2/CheekPuffSuck", "v2/CheekPuffSuckLeft", "v2/CheekPuffSuckLeftNegative", "v2/CheekPuffSuckNegative",
    "v2/CheekPuffSuckRight", "v2/CheekPuffSuckRightNegative", "v2/CheekSquint", "v2/CheekSquintLeft",
    "v2/CheekSquintLeftNegative", "v2/CheekSquintNegative", "v2/CheekSquintRight",
    "v2/CheekSquintRightNegative", "v2/CheekSuck", "v2/CheekSuckLeft", "v2/CheekSuckLeftNegative",
    "v2/CheekSuckNegative", "v2/CheekSuckRight", "v2/CheekSuckRightNegative", "v2/EyeClosed",
    "v2/EyeClosedLeft", "v2/EyeClosedLeftNegative", "v2/EyeClosedNegative", "v2/EyeClosedRight",
    "v2/EyeClosedRightNegative", "v2/EyeLeftX", "v2/EyeLeftXNegative", "v2/EyeLeftY", "v2/EyeLeftYNegative",
    "v2/EyeLid", "v2/EyeLidLeft", "v2/EyeLidLeftNegative", "v2/EyeLidNegative", "v2/EyeLidRight",
    "v2/EyeLidRightNegative", "v2/EyeOpen", "v2/EyeOpenLeft", "v2/EyeOpenLeftNegative", "v2/EyeOpenNegative",
    "v2/EyeOpenRight", "v2/EyeOpenRightNegative", "v2/EyeRightX", "v2/EyeRightXNegative", "v2/EyeRightY",
    "v2/EyeRightYNegative", "v2/EyeSquint", "v2/EyeSquintLeft", "v2/EyeSquintLeftNegative",
    "v2/EyeSquintNegative", "v2/EyeSquintRight", "v2/EyeSquintRightNegative", "v2/EyeWide", "v2/EyeWideLeft",
    "v2/EyeWideLeftNegative", "v2/EyeWideNegative", "v2/EyeWideRight", "v2/EyeWideRightNegative", "v2/EyeX",
    "v2/EyeXNegative", "v2/EyeY", "v2/EyeYNegative", "v2/EyesSquint", "v2/EyesSquintNegative",
    "v2/Head/Pitch", "v2/Head/PitchNegative", "v2/Head/PosX", "v2/Head/PosXNegative", "v2/Head/PosY",
    "v2/Head/PosYNegative", "v2/Head/PosZ", "v2/Head/PosZNegative", "v2/Head/Roll", "v2/Head/RollNegative",
    "v2/Head/Yaw", "v2/Head/YawNegative", "v2/JawBackward", "v2/JawBackwardNegative", "v2/JawClench",
    "v2/JawClenchNegative", "v2/JawForward", "v2/JawForwardNegative", "v2/JawLeft", "v2/JawLeftNegative",
    "v2/JawMandibleRaise", "v2/JawMandibleRaiseNegative", "v2/JawOpen", "v2/JawOpenNegative", "v2/JawRight",
    "v2/JawRightNegative", "v2/JawX", "v2/JawXNegative", "v2/JawZ", "v2/JawZNegative", "v2/LipFunnel",
    "v2/LipFunnelLower", "v2/LipFunnelLowerLeft", "v2/LipFunnelLowerLeftNegative",
    "v2/LipFunnelLowerNegative", "v2/LipFunnelLowerRight", "v2/LipFunnelLowerRightNegative",
    "v2/LipFunnelNegative", "v2/LipFunnelUpper", "v2/LipFunnelUpperLeft", "v2/LipFunnelUpperLeftNegative",
    "v2/LipFunnelUpperNegative", "v2/LipFunnelUpperRight", "v2/LipFunnelUpperRightNegative", "v2/LipPucker",
    "v2/LipPuckerLeft", "v2/LipPuckerLeftNegative", "v2/LipPuckerLower", "v2/LipPuckerLowerLeft",
    "v2/LipPuckerLowerLeftNegative", "v2/LipPuckerLowerNegative", "v2/LipPuckerLowerRight",
    "v2/LipPuckerLowerRightNegative", "v2/LipPuckerNegative", "v2/LipPuckerRight",
    "v2/LipPuckerRightNegative", "v2/LipPuckerUpper", "v2/LipPuckerUpperLeft",
    "v2/LipPuckerUpperLeftNegative", "v2/LipPuckerUpperNegative", "v2/LipPuckerUpperRight",
    "v2/LipPuckerUpperRightNegative", "v2/LipSuck", "v2/LipSuckCornerLeft", "v2/LipSuckCornerLeftNegative",
    "v2/LipSuckCornerRight", "v2/LipSuckCornerRightNegative", "v2/LipSuckFunnelLower",
    "v2/LipSuckFunnelLowerLeft", "v2/LipSuckFunnelLowerLeftNegative", "v2/LipSuckFunnelLowerNegative",
    "v2/LipSuckFunnelLowerRight", "v2/LipSuckFunnelLowerRightNegative", "v2/LipSuckFunnelUpper",
    "v2/LipSuckFunnelUpperLeft", "v2/LipSuckFunnelUpperLeftNegative", "v2/LipSuckFunnelUpperNegative",
    "v2/LipSuckFunnelUpperRight", "v2/LipSuckFunnelUpperRightNegative", "v2/LipSuckLower",
    "v2/LipSuckLowerLeft", "v2/LipSuckLowerLeftNegative", "v2/LipSuckLowerNegative", "v2/LipSuckLowerRight",
    "v2/LipSuckLowerRightNegative", "v2/LipSuckNegative", "v2/LipSuckUpper", "v2/LipSuckUpperLeft",
    "v2/LipSuckUpperLeftNegative", "v2/LipSuckUpperNegative", "v2/LipSuckUpperRight",
    "v2/LipSuckUpperRightNegative", "v2/Max", "v2/MaxNegative", "v2/MouthClosed", "v2/MouthClosedNegative",
    "v2/MouthCornerPullLeft", "v2/MouthCornerPullLeftNegative", "v2/MouthCornerPullRight",
    "v2/MouthCornerPullRightNegative", "v2/MouthCornerSlantLeft", "v2/MouthCornerSlantLeftNegative",
    "v2/MouthCornerSlantRight", "v2/MouthCornerSlantRightNegative", "v2/MouthCornerY", "v2/MouthCornerYLeft",
    "v2/MouthCornerYLeftNegative", "v2/MouthCornerYNegative", "v2/MouthCornerYRight",
    "v2/MouthCornerYRightNegative", "v2/MouthDimple", "v2/MouthDimpleLeft", "v2/MouthDimpleLeftNegative",
    "v2/MouthDimpleNegative", "v2/MouthDimpleRight", "v2/MouthDimpleRightNegative", "v2/MouthFrownLeft",
    "v2/MouthFrownLeftNegative", "v2/MouthFrownRight", "v2/MouthFrownRightNegative", "v2/MouthLowerDown",
    "v2/MouthLowerDownLeft", "v2/MouthLowerDownLeftNegative", "v2/MouthLowerDownNegative",
    "v2/MouthLowerDownRight", "v2/MouthLowerDownRightNegative", "v2/MouthLowerLeft",
    "v2/MouthLowerLeftNegative", "v2/MouthLowerRight", "v2/MouthLowerRightNegative", "v2/MouthLowerX",
    "v2/MouthLowerXNegative", "v2/MouthOpen", "v2/MouthOpenNegative", "v2/MouthPress", "v2/MouthPressLeft",
    "v2/MouthPressLeftNegative", "v2/MouthPressNegative", "v2/MouthPressRight", "v2/MouthPressRightNegative",
    "v2/MouthRaiserLower", "v2/MouthRaiserLowerNegative", "v2/MouthRaiserUpper",
    "v2/MouthRaiserUpperNegative", "v2/MouthSadLeft", "v2/MouthSadLeftNegative", "v2/MouthSadRight",
    "v2/MouthSadRightNegative", "v2/MouthSmileLeft", "v2/MouthSmileLeftNegative", "v2/MouthSmileRight",
    "v2/MouthSmileRightNegative", "v2/MouthStretch", "v2/MouthStretchLeft", "v2/MouthStretchLeftNegative",
    "v2/MouthStretchNegative", "v2/MouthStretchRight", "v2/MouthStretchRightNegative", "v2/MouthTightener",
    "v2/MouthTightenerLeft", "v2/MouthTightenerLeftNegative", "v2/MouthTightenerNegative",
    "v2/MouthTightenerRight", "v2/MouthTightenerRightNegative", "v2/MouthTightenerStretch",
    "v2/MouthTightenerStretchLeft", "v2/MouthTightenerStretchLeftNegative",
    "v2/MouthTightenerStretchNegative", "v2/MouthTightenerStretchRight",
    "v2/MouthTightenerStretchRightNegative", "v2/MouthUpperDeepenLeft", "v2/MouthUpperDeepenLeftNegative",
    "v2/MouthUpperDeepenRight", "v2/MouthUpperDeepenRightNegative", "v2/MouthUpperLeft",
    "v2/MouthUpperLeftNegative", "v2/MouthUpperRight", "v2/MouthUpperRightNegative", "v2/MouthUpperUp",
    "v2/MouthUpperUpLeft", "v2/MouthUpperUpLeftNegative", "v2/MouthUpperUpNegative", "v2/MouthUpperUpRight",
    "v2/MouthUpperUpRightNegative", "v2/MouthUpperX", "v2/MouthUpperXNegative", "v2/MouthX",
    "v2/MouthXNegative", "v2/NasalConstrictLeft", "v2/NasalConstrictLeftNegative", "v2/NasalConstrictRight",
    "v2/NasalConstrictRightNegative", "v2/NasalDilationLeft", "v2/NasalDilationLeftNegative",
    "v2/NasalDilationRight", "v2/NasalDilationRightNegative", "v2/NeckFlexLeft", "v2/NeckFlexLeftNegative",
    "v2/NeckFlexRight", "v2/NeckFlexRightNegative", "v2/NoseSneer", "v2/NoseSneerLeft",
    "v2/NoseSneerLeftNegative", "v2/NoseSneerNegative", "v2/NoseSneerRight", "v2/NoseSneerRightNegative",
    "v2/PupilDiameter", "v2/PupilDiameterLeft", "v2/PupilDiameterLeftNegative", "v2/PupilDiameterNegative",
    "v2/PupilDiameterRight", "v2/PupilDiameterRightNegative", "v2/PupilDilation", "v2/PupilDilationNegative",
    "v2/SmileFrown", "v2/SmileFrownLeft", "v2/SmileFrownLeftNegative", "v2/SmileFrownNegative",
    "v2/SmileFrownRight", "v2/SmileFrownRightNegative", "v2/SmileSad", "v2/SmileSadLeft",
    "v2/SmileSadLeftNegative", "v2/SmileSadNegative", "v2/SmileSadRight", "v2/SmileSadRightNegative",
    "v2/SoftPalateClose", "v2/SoftPalateCloseNegative", "v2/ThroatSwallow", "v2/ThroatSwallowNegative",
    "v2/TongueArchY", "v2/TongueArchYNegative", "v2/TongueBendDown", "v2/TongueBendDownNegative",
    "v2/TongueCurlUp", "v2/TongueCurlUpNegative", "v2/TongueDown", "v2/TongueDownNegative", "v2/TongueFlat",
    "v2/TongueFlatNegative", "v2/TongueLeft", "v2/TongueLeftNegative", "v2/TongueOut", "v2/TongueOutNegative",
    "v2/TongueRight", "v2/TongueRightNegative", "v2/TongueRoll", "v2/TongueRollNegative", "v2/TongueShape",
    "v2/TongueShapeNegative", "v2/TongueSquish", "v2/TongueSquishNegative", "v2/TongueTwistLeft",
    "v2/TongueTwistLeftNegative", "v2/TongueTwistRight", "v2/TongueTwistRightNegative", "v2/TongueUp",
    "v2/TongueUpNegative", "v2/TongueX", "v2/TongueXNegative", "v2/TongueY", "v2/TongueYNegative",
))

VRCFT_BINARY_PARAMETERS = frozenset((
    "BrowDownLeft", "BrowDownRight", "BrowInnerUpLeft", "BrowInnerUpRight", "BrowOuterUpLeft",
    "BrowOuterUpRight", "BrowsDown", "BrowsInnerUp", "BrowsOuterUp", "CheekPuffLeft", "CheekPuffRight",
    "CheekSquintLeft", "CheekSquintRight", "CheekSuck", "CheeksSquint", "CombinedEyeLid",
    "CombinedEyeLidExpanded", "CombinedEyeLidExpandedSqueeze", "EyeSquintLeft", "EyeSquintRight", "EyeWiden",
    "EyesDilation", "EyesPupilDiameter", "EyesSqueeze", "EyesSquint", "EyesX", "EyesY", "JawForward",
    "JawLeft", "JawOpen", "JawOpenApe", "JawOpenForward", "JawOpenOverlay", "JawOpenPuff", "JawOpenPuffLeft",
    "JawOpenPuffRight", "JawOpenSuck", "JawRight", "JawX", "LeftEyeLid", "LeftEyeLidExpanded",
    "LeftEyeLidExpandedSqueeze", "LeftEyeSqueeze", "LeftEyeWiden", "LeftEyeX", "LeftEyeY", "Max",
    "MouthApeShape", "MouthDimple", "MouthDimpleLeft", "MouthDimpleRight", "MouthLower", "MouthLowerDownApe",
    "MouthLowerDownInside", "MouthLowerDownLeft", "MouthLowerDownLeftApe", "MouthLowerDownLeftLowerInside",
    "MouthLowerDownLeftOverlay", "MouthLowerDownLeftPout", "MouthLowerDownLeftPuffLeft",
    "MouthLowerDownLeftSuck", "MouthLowerDownLowerInside", "MouthLowerDownOverlay", "MouthLowerDownPout",
    "MouthLowerDownPuff", "MouthLowerDownPuffLeft", "MouthLowerDownPuffRight", "MouthLowerDownRight",
    "MouthLowerDownRightApe", "MouthLowerDownRightLowerInside", "MouthLowerDownRightOverlay",
    "MouthLowerDownRightPout", "MouthLowerDownRightPuffRight", "MouthLowerDownRightSuck",
    "MouthLowerDownSuck", "MouthLowerInside", "MouthLowerInsideOverturn", "MouthLowerLeft",
    "MouthLowerOverlay", "MouthLowerOverturn", "MouthLowerRight", "MouthPout", "MouthPress", "MouthPressLeft",
    "MouthPressRight", "MouthRaiserLower", "MouthRaiserUpper", "MouthSadLeft", "MouthSadRight",
    "MouthSmileLeft", "MouthSmileRight", "MouthStretch", "MouthStretchLeft", "MouthStretchRight",
    "MouthTightener", "MouthTightenerLeft", "MouthTightenerRight", "MouthUpper", "MouthUpperInside",
    "MouthUpperInsideOverturn", "MouthUpperLeft", "MouthUpperOverturn", "MouthUpperRight", "MouthUpperUpApe",
    "MouthUpperUpInside", "MouthUpperUpLeft", "MouthUpperUpLeftApe", "MouthUpperUpLeftOverlay",
    "MouthUpperUpLeftPout", "MouthUpperUpLeftPuffLeft", "MouthUpperUpLeftSuck", "MouthUpperUpLeftUpperInside",
    "MouthUpperUpOverlay", "MouthUpperUpPout", "MouthUpperUpPuff", "MouthUpperUpPuffLeft",
    "MouthUpperUpPuffRight", "MouthUpperUpRight", "MouthUpperUpRightApe", "MouthUpperUpRightOverlay",
    "MouthUpperUpRightPout", "MouthUpperUpRightPuffRight", "MouthUpperUpRightSuck",
    "MouthUpperUpRightUpperInside", "MouthUpperUpSuck", "MouthUpperUpUpperInside", "MouthX", "NoseSneer",
    "NoseSneerLeft", "NoseSneerRight", "PuffLeftLowerOverturn", "PuffLeftOverturn", "PuffLeftUpperOverturn",
    "PuffLowerOverturn", "PuffOverturn", "PuffRightLowerOverturn", "PuffRightOverturn",
    "PuffRightUpperOverturn", "PuffSuck", "PuffSuckLeft", "PuffSuckRight", "PuffUpperOverturn", "RightEyeLid",
    "RightEyeLidExpanded", "RightEyeLidExpandedSqueeze", "RightEyeSqueeze", "RightEyeWiden", "RightEyeX",
    "RightEyeY", "SmileApe", "SmileLeftApe", "SmileLeftLowerOverturn", "SmileLeftOverlay",
    "SmileLeftOverturn", "SmileLeftPout", "SmileLeftUpperOverturn", "SmileLowerOverturn", "SmileOverlay",
    "SmileOverturn", "SmilePout", "SmileRightApe", "SmileRightLowerOverturn", "SmileRightOverlay",
    "SmileRightOverturn", "SmileRightPout", "SmileRightUpperOverturn", "SmileSad", "SmileSadLeft",
    "SmileSadRight", "SmileUpperOverturn", "TongueDown", "TongueDownLeftMorph", "TongueDownRightMorph",
    "TongueLeft", "TongueLongStep1", "TongueLongStep2", "TongueRight", "TongueRoll", "TongueSteps",
    "TongueUp", "TongueUpLeftMorph", "TongueUpRightMorph", "TongueX", "TongueY", "v2/BrowDown",
    "v2/BrowDownLeft", "v2/BrowDownRight", "v2/BrowExpression", "v2/BrowExpressionLeft",
    "v2/BrowExpressionRight", "v2/BrowInnerUp", "v2/BrowInnerUpLeft", "v2/BrowInnerUpRight",
    "v2/BrowLowererLeft", "v2/BrowLowererRight", "v2/BrowOuterUp", "v2/BrowOuterUpLeft",
    "v2/BrowOuterUpRight", "v2/BrowPinchLeft", "v2/BrowPinchRight", "v2/BrowUp", "v2/BrowUpLeft",
    "v2/BrowUpRight", "v2/CheekPuffLeft", "v2/CheekPuffRight", "v2/CheekPuffSuck", "v2/CheekPuffSuckLeft",
    "v2/CheekPuffSuckRight", "v2/CheekSquint", "v2/CheekSquintLeft", "v2/CheekSquintRight", "v2/CheekSuck",
    "v2/CheekSuckLeft", "v2/CheekSuckRight", "v2/EyeClosed", "v2/EyeClosedLeft", "v2/EyeClosedRight",
    "v2/EyeLeftX", "v2/EyeLeftY", "v2/EyeLid", "v2/EyeLidLeft", "v2/EyeLidRight", "v2/EyeOpen",
    "v2/EyeOpenLeft", "v2/EyeOpenRight", "v2/EyeRightX", "v2/EyeRightY", "v2/EyeSquint", "v2/EyeSquintLeft",
    "v2/EyeSquintRight", "v2/EyeWide", "v2/EyeWideLeft", "v2/EyeWideRight", "v2/EyeX", "v2/EyeY",
    "v2/EyesSquint", "v2/Head/Pitch", "v2/Head/PosX", "v2/Head/PosY", "v2/Head/PosZ", "v2/Head/Roll",
    "v2/Head/Yaw", "v2/JawBackward", "v2/JawClench", "v2/JawForward", "v2/JawLeft", "v2/JawMandibleRaise",
    "v2/JawOpen", "v2/JawRight", "v2/JawX", "v2/JawZ", "v2/LipFunnel", "v2/LipFunnelLower",
    "v2/LipFunnelLowerLeft", "v2/LipFunnelLowerRight", "v2/LipFunnelUpper", "v2/LipFunnelUpperLeft",
    "v2/LipFunnelUpperRight", "v2/LipPucker", "v2/LipPuckerLeft", "v2/LipPuckerLower",
    "v2/LipPuckerLowerLeft", "v2/LipPuckerLowerRight", "v2/LipPuckerRight", "v2/LipPuckerUpper",
    "v2/LipPuckerUpperLeft", "v2/LipPuckerUpperRight", "v2/LipSuck", "v2/LipSuckCornerLeft",
    "v2/LipSuckCornerRight", "v2/LipSuckFunnelLower", "v2/LipSuckFunnelLowerLeft",
    "v2/LipSuckFunnelLowerRight", "v2/LipSuckFunnelUpper", "v2/LipSuckFunnelUpperLeft",
    "v2/LipSuckFunnelUpperRight", "v2/LipSuckLower", "v2/LipSuckLowerLeft", "v2/LipSuckLowerRight",
    "v2/LipSuckUpper", "v2/LipSuckUpperLeft", "v2/LipSuckUpperRight", "v2/Max", "v2/MouthClosed",
    "v2/MouthCornerPullLeft", "v2/MouthCornerPullRight", "v2/MouthCornerSlantLeft",
    "v2/MouthCornerSlantRight", "v2/MouthCornerY", "v2/MouthCornerYLeft", "v2/MouthCornerYRight",
    "v2/MouthDimple", "v2/MouthDimpleLeft", "v2/MouthDimpleRight", "v2/MouthFrownLeft", "v2/MouthFrownRight",
    "v2/MouthLowerDown", "v2/MouthLowerDownLeft", "v2/MouthLowerDownRight", "v2/MouthLowerLeft",
    "v2/MouthLowerRight", "v2/MouthLowerX", "v2/MouthOpen", "v2/MouthPress", "v2/MouthPressLeft",
    "v2/MouthPressRight", "v2/MouthRaiserLower", "v2/MouthRaiserUpper", "v2/MouthSadLeft", "v2/MouthSadRight",
    "v2/MouthSmileLeft", "v2/MouthSmileRight", "v2/MouthStretch", "v2/MouthStretchLeft",
    "v2/MouthStretchRight", "v2/MouthTightener", "v2/MouthTightenerLeft", "v2/MouthTightenerRight",
    "v2/MouthTightenerStretch", "v2/MouthTightenerStretchLeft", "v2/MouthTightenerStretchRight",
    "v2/MouthUpperDeepenLeft", "v2/MouthUpperDeepenRight", "v2/MouthUpperLeft", "v2/MouthUpperRight",
    "v2/MouthUpperUp", "v2/MouthUpperUpLeft", "v2/MouthUpperUpRight", "v2/MouthUpperX", "v2/MouthX",
    "v2/NasalConstrictLeft", "v2/NasalConstrictRight", "v2/NasalDilationLeft", "v2/NasalDilationRight",
    "v2/NeckFlexLeft", "v2/NeckFlexRight", "v2/NoseSneer", "v2/NoseSneerLeft", "v2/NoseSneerRight",
    "v2/PupilDiameter", "v2/PupilDiameterLeft", "v2/PupilDiameterRight", "v2/PupilDilation", "v2/SmileFrown",
    "v2/SmileFrownLeft", "v2/SmileFrownRight", "v2/SmileSad", "v2/SmileSadLeft", "v2/SmileSadRight",
    "v2/SoftPalateClose", "v2/ThroatSwallow", "v2/TongueArchY", "v2/TongueBendDown", "v2/TongueCurlUp",
    "v2/TongueDown", "v2/TongueFlat", "v2/TongueLeft", "v2/TongueOut", "v2/TongueRight", "v2/TongueRoll",
    "v2/TongueShape", "v2/TongueSquish", "v2/TongueTwistLeft", "v2/TongueTwistRight", "v2/TongueUp",
    "v2/TongueX", "v2/TongueY",
))

_LOWER = {n.lower(): n for n in VRCFT_PARAMETERS}
_LOWER_BINARY = {n.lower(): n for n in VRCFT_BINARY_PARAMETERS}


def vrcft_conflict(name):
    """The VRCFaceTracking parameter that would also drive an avatar parameter called `name`,
    or None. Compared case-insensitively to be safe."""
    name = (name or "").lower()
    suffixes = [name] + [name.split("/", i)[-1] for i in range(1, name.count("/") + 1)]
    for s in suffixes:
        if s in _LOWER:
            return _LOWER[s]
        # binary bit "<name><digits>": try every split, the name itself may end in a digit
        # (VRCFT's regex is "<name>\\d+", e.g. TongueLongStep2 + 4 -> "TongueLongStep24")
        digits = len(s) - len(s.rstrip("0123456789"))
        for k in range(1, digits + 1):
            if s[:-k] in _LOWER_BINARY:
                return _LOWER_BINARY[s[:-k]] + "<n>"
    return None
